#import "@preview/tablem:0.3.0": tablem, three-line-table
#import "@preview/booktabs:0.0.4": *
#import "@preview/mitex:0.2.5": *

= Increased Progressivity of the Pension System
This section will detail the macroeconomic, welfare and efficiency effects, as well as the fiscal sustainability, of increasing the progressivity of the pension system.

We start from the initial equilibrium obtained in the previous section, which was defined as $t=2021$. We progressively change the value of $lambda$ starting from $t=2022$ and calculate the transition path towards the new equilibrium state $t = infinity$.

We are interested in understanding the effects on macroeconomic aggregates, as well as on welfare and efficiency, between both equilibrium states.

== Calculations of effects on welfare and efficiency

In order to account for changes in the well-being of the agents, we will use the so-called *Hicksian Equivalence #footnote[Compensation Variation]*.

Given that the household utility function is homogeneous @fehr2013should, we have that the following equality holds.

#mitex(
  `
\begin{equation}
u\left[(1+\phi) c_j,(1+\phi) \ell_j\right]=(1+\phi) u\left[c_j, \ell_j\right]
\end{equation}
  `
)

If consumption and leisure were simultaneously increased by a factor of $1 + phi.alt$ at any age, lifetime utility would increase by the same factor. If we assume that an individual in state $z_j$ has utility $V_(2021)(z_j)$ in the initial equilibrium and $V_(t)(z_j)$ in the second long-run equilibrium after the policy, $t > 2021$.

The compensation variation between the reform scenario and the baseline scenario for the individual with status $z_j$ would be

#mitex(
  `
\begin{equation}
\phi=\frac{V_t\left(z_j\right)}{V_{2021}\left(z_j\right)}-1
\end{equation}
  `
)

where $phi.alt$ indicates the percentage change in both consumption and leisure that the individual in state $z_j$ would require in the initial state to be at least as well off as after the policy reform. If $phi.alt > 0$, the reform improves the well-being of this individual, and vice versa.

The solid line in the figure below shows a possible cohort-specific consequence on well-being that individuals may experience as a result of a policy#footnote[A representative agent is considered for each cohort.]. The policy redistributes wealth from current cohorts to future cohorts#footnote[The axis $x$ of the graph indicates the birth year of the cohorts. Since households begin their working lives at age 20, following the example of @fehr2013should, the last cohort to enter the labor market was born in 1998, as the first equilibrium state corresponds to 2008. When referring to future generations, this means generations born after 2009.]


To isolate the effects solely attributable to the efficiency of the reform, @alma99576423502432 pioneered the introduction of a new agent into the model: the Lump-Sum Redistribution Authority (LSRA). This agent performs a hypothetical task in an independent simulation, redistributing and compensating for the benefits or losses generated by the policy. First, this agent makes transfers or imposes taxes on all economically active generations in the year immediately preceding the policy's implementation, aiming to ensure they are as well off as they were in the initial equilibrium state after the policy. Therefore, its compensating variation is equal to 0. Subsequently, as a consequence of this redistributive operation, the LSRA may have incurred debt or accumulated assets. The LSRA redistributes this debt or assets to future generations in such a way that everyone receives the same compensating variation. This variation can be interpreted as a measure of efficiency. @fehr2013should If this variation is positive, the reform is considered to be Pareto improved after compensation.

== Effects of increased progressivity

We are interested in calculating the effects of increasing the progressivity of the pension system and calculating the path to the second equilibrium state for the values ​​of $lambda in {0.1, 0.2, dots , 1.0}$. This intervention has two latent effects on the system. The first: Under the earning points system, a portion of workers' pension contributions is recognized as implicit savings. Under the system where the pension is independent of income history ($lambda = 1$), the contribution is considered an implicit tax. Thus, the transition to a pension system with a flat pension increases distortions in the labor supply and decreases welfare. The second: The pension system independent of income history ($lambda = 1$) also functions as insurance against labor market risks, which tends to improve welfare.

=== Macroeconomic effects

=== Well-being and Efficiency

We use Hicksian variation as a measure of the effects on well-being for different cohorts. We would like to answer:

- Are retirees affected or benefited? How are they affected by increases in consumption taxes? Are those in the formal or informal sectors more affected or harmed?
- Are current working-age generations affected or benefited?
- Here the intra-generational redistribution from rich towards poor households induced by the progressive pension formula becomes most obvious.
- Are the new generations affected or benefited?
- What about the overall measure of the LSRA? That is, the welfare effects after compensation payments.

The evolution of welfare after compensation is depicted in the right part of Table 5. We find that the
reform induces losses for any future generation of 0.46% of initial resources.


The introduction of flat pensions comes along with two major efficiency consequences: 
- on the one hand, insurance provision against labor market risk causes efficiency to rise while, 
- on the other hand, increasing labor market distortions reduce it. 


We find in this reform scenario that the latter outweighs the former and therefore the introduction of completely flat pension benefits is Pareto inferior.



#figure(
table(
  columns: (130pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt) ,
  align: (left, center, center),
  toprule(), // added by this package
  table.header(
    [*Año*],
    [*2022*],
    [*2030*],
    [*2040*],
    [*2050*],
    [*2060*],
    [*2070*],
    [*2080*],
    [*2090*],
    [$infinity$],
  ),

  midrule(), // added by this package
  table.cell(colspan: 10)[*Agregados Macroeconómicos*],
  [PIB],[-0.32],[-2.15],[-3.56],[-4.34],[-5.15],[-5.17],[-5.19],[-5.19],[-5.19],        
  [Trabajo],[-0.82],[-1.35],[-1.29],[-1.26],[-1.25],[-1.24],[-1.23],[-1.23],[-1.23],     
  [Capital],[-0.0],[-2.63],[-4.93],[-6.18],[-7.05],[-7.3],[-7.53],[-7.51],[-7.51],
  [],[],[],[],[],[],[],[],[],[],
  
  cmidrule(start: 0, end: -1), // added by this package

  table.cell(colspan: 10)[*Precios*],
  [Salario],[0.51],[-0.81],[-2.3],[-3.11],[-3.58],[-4.01],[-4.03],[-4.03],[-4.03],
  [Tasa de interés],[-0.39],[0.63],[1.83],[2.49],[2.87],[3.09],[3.22],[3.21],[3.21],
  [Impuesto al capital],[0.36],[4.54],[8.18],[10.21],[11.38],[12.05],[12.08],[12.07],[12.07],
  [],[],[],[],[],[],[],[],[],[],

  cmidrule(start: 0, end: -1), // added by this package

  table.cell(colspan: 10)[*Sistema de Pensiones*],
  [Gasto en Pensiones#footnote[en % de PIB]],[2.44],[2.87],[2.84],[2.84],[2.84],[2.84],[2.84],[2.84],[2.84],
  [Tasa de Contribución],[-0.0],[17.62],[16.35],[16.35],[16.35],[16.35],[16.35],[16.35],[16.35],
  [],[],[],[],[],[],[],[],[],[],

  cmidrule(start: 0, end: -1), // added by this package

  bottomrule() // added by this package
  )
  , caption : [Welfare effects of flat pensions (base model version).]
) <table-flat-pension>

Referencing @table-flat-pension in-text using its label.


#figure(
table(
  columns: (125pt, 90pt, 100pt, 100pt, 100pt) ,
  align: (center, center, center),
  toprule(), // added by this package
  table.header(
    [*Birth Year*],
    [*Years in 2021*],
    table.cell(colspan: 2)[*Sin LSRA*],
    [*Con LSRA*],

    cmidrule(start: 2, end: 4), // added by this package
    [],
    [],
    table.cell(colspan: 2)[*Por tipo de Empleo*],
    [],


  ),

  midrule(), // added by this package
  [*Retired*],[],[*Formal*],[*Informal*],[],
  
  [1930], [91], [1.19], [0.53], [0.0],
  [1956], [65], [3.93], [2.47], [0.0],

  [],[],[],[],[],
  cmidrule(start: 0, end: -1), // added by this package

  [*Workers*],[],[*Formal*],[*Informal*],[],
  [1960], [61], [-7.87], [2.01], [0.0],
  [1970], [51], [-4.43], [0.80], [0.0],
  [1980], [41], [-0.65], [0.52], [0.0],
  [1990], [31], [0.47], [0.28], [0.0],
  [2000], [21], [-0.73], [-0.73], [0.0],

  [],[],[],[],[],
  cmidrule(start: 0, end: -1), // added by this package

  [*Future Generations*],[],[],[],[],

  [2012], [19], [], [], [-0.13],
  [2020], [1], [], [], [-0.13],
  [2040], [-], [], [], [-0.13],
  [2060], [-], [], [], [-0.13],

  bottomrule() // added by this package


  )
  , caption : [Welfare effects of flat pensions (base model version).]
) 

#figure(
table(
  columns: (130pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt) ,
  align: (left, center, center),
  toprule(), // added by this package
  table.header(
    [*$lambda$*],
    [*0.1*],
    [*0.2*],
    [*0.3*],
    [*0.4*],
    [*0.5*],
    [*0.6*],
    [*0.7*],
    [*0.8*],
    [*0.9*]
  ),

  midrule(), // added by this package
  table.cell(colspan: 10)[*Macroeconomic Aggregates*],
  [GDP],[-0.56], [-1.12], [-1.69], [-2.26], [-2.82], [-3.39], [-3.96], [-4.51], [-5.03],      
  [Work],[-0.11], [-0.24], [-0.36], [-0.48], [-0.6], [-0.73], [-0.85], [-0.98], [-1.1],
  [Capital],[-0.82], [-1.66], [-2.5], [-3.33], [-4.16], [-4.99], [-5.82], [-6.63], [-7.37],
  [],[],[],[],[],[],[],[],[],[],
  
  cmidrule(start: 0, end: -1), // added by this package

  table.cell(colspan: 10)[*Prices*],
  [Wage],[-0.44], [-0.88], [-1.33], [-1.78], [-2.23], [-2.68], [-3.13], [-3.57], [-3.97],
  [Interest rate], [0.34], [0.69], [1.05], [1.41], [1.77], [2.14], [2.5], [2.86], [3.2],
  [Capital tax],[1.29], [2.61], [3.95], [5.3], [6.67], [8.06], [9.44], [10.83], [12.12],
  [],[],[],[],[],[],[],[],[],[],

  cmidrule(start: 0, end: -1), // added by this package

  table.cell(colspan: 10)[*Sistema de Pensiones*],
  [Pensions expenditure#footnote[en % de PIB]],[2.48], [2.52], [2.56], [2.6], [2.64], [2.68], [2.72], [2.76], [2.8],
  [Contribution Rate],[1.57], [3.16], [4.76], [6.37], [8.0], [9.64], [11.3], [12.97], [14.66],
  [],[],[],[],[],[],[],[],[],[],

  cmidrule(start: 0, end: -1), // added by this package

  table.cell(colspan: 10)[*Eficiencia Agregada*],
  [With LSRA],[-0.01], [-0.02], [-0.03], [-0.041], [-0.053], [-0.065], [-0.079], [-0.094], [-0.111],
  [],[],[],[],[],[],[],[],[],[],

  bottomrule() // added by this package
  )
  , caption : [Aggregate efficiency effects of alternative progressivity levels.]
) 






#figure(
table(
  columns: (130pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt, 40pt) ,
  align: (left, center, center),
  toprule(), // added by this package
  table.header(
    [*Año*],
    [*2022*],
    [*2030*],
    [*2040*],
    [*2050*],
    [*2060*],
    [*2070*],
    [*2080*],
    [*2090*],
    [$infinity$],
  ),

  midrule(), // added by this package
  table.cell(colspan: 10)[*Agregados Macroeconómicos*],
  [GDP],[-0.25], [0.84], [0.38], [-0.0], [-0.22], [-0.34], [-0.41], [-0.44], [-0.47],        
  [Work],[-0.65], [4.02], [3.69], [3.71], [3.71], [3.72], [3.72], [3.72], [3.72],    
  [Capital],[-0.0], [-1.06], [-1.61], [-2.22], [-2.56], [-2.75], [-2.86], [-2.92], [-2.96],
  [],[],[],[],[],[],[],[],[],[],
  
  cmidrule(start: 0, end: -1), // added by this package

  table.cell(colspan: 10)[*Precios*],
  [Wage],[0.4], [-3.06], [-3.2], [-3.58], [-3.79], [-3.91], [-3.98], [-4.02], [-4.04],
  [Interest rate],[-0.31], [2.44], [2.56], [2.87], [3.05], [3.15], [3.2], [3.23], [3.25],
  [Capital tax],[0.11], [-0.59], [0.3], [1.23], [1.75], [2.05], [2.22], [2.31], [2.37],
  [],[],[],[],[],[],[],[],[],[],

  cmidrule(start: 0, end: -1), // added by this package

  table.cell(colspan: 10)[*Sistema de Pensiones*],
  [Pensions expenditure#footnote[en % de PIB]],[2.42], [2.71], [2.97], [2.97], [2.97], [2.97], [2.97], [2.97], [2.97],
  [Contribution Rate],[-4.16], [-2.05], [7.6], [7.6], [7.6], [7.6], [7.6], [7.6], [7.6],
  [],[],[],[],[],[],[],[],[],[],

  cmidrule(start: 0, end: -1), // added by this package

  table.cell(colspan: 10)[*Eficiencia Agregada*],
  [With LSRA],[], [], [], [], [], [], [], [], [1.05],
  [],[],[],[],[],[],[],[],[],[],

  bottomrule() // added by this package
  )
  , caption : [Welfare effects of flat pensions (base model version) and Complete Formal Labor Market.]
)



